name: Run Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn build --if-present
        yarn test
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        # Github token
        github-token: ${{ secrets.GITHUB_TOKEN }}
